steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'gcr.io/mtdashboard-backend', '-f', 'Dockerfile.prod', '.']
    dir: 'backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'gcr.io/mtdashboard-frontend', '-f', 'Dockerfile.prod', '.']
    dir: 'frontend'
images:
  - 'gcr.io/dashboard-backend'
  - 'gcr.io/mtdashboard-frontend' 
